version: '3'
services:
  flask:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    volumes:
     - .:/usr/src/app
  nginx:
    image: webapp-nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 5000:80
    depends_on:
      - flask

